name: WeatherApp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2 # Añade esta línea

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png" # Usa esta clave general

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
